### PR TITLE
Update assays.tsv

### PR DESCRIPTION
**Pull request by Daniel-Olson**
Added new terms from the FARS functional assessment to the assays template.

### CODE REVIEW

**Review by matentzn — CHANGES_REQUESTED** [review]
I dont know exactly how, will needs probably Emilys help, but the diff of this PR needs to be reduced to only include _actual_ changes. There should be _no_ red line in the PR.

Probably an issue with line ending encoding?

**Comment by Daniel-Olson** [comment]
Hey Nico. Thanks for looking into this. The red lines are the result of adding two new columns (anatomical site, etc.) to the template. The other issue was the sorting. Also, I believe someone previously added terms without sorting. 

I did fix some errors that Emily Caught.

**Comment by matentzn** [comment]
@Daniel-Olson I am pretty sure the OBI team will not like all this red, so I would suggest to make this a 2 stage process. 

1. First, add all the terms using _only_ the columns currently provided by the assay template. This should only highlight the actual additions.
2. Do not sort the file.
3. Request an ID range from the OBI issue tracker now and use that for terms

We will then:

1. Request (in an OBI issue) to add an empty anatomical entity column, which an OBI team member will do (Not us).
2. When this is done, we add the anatomical entity links to the assay template in a third PR.

I know its a lot, but I will help you through it - contributing to public ontologies has to be a bit painful in order to protect them from decay.

**Comment by matentzn** [comment]
Ok nice. Diff looks much better.

Now you should request an ID range from OBI by just making an issue on their issue tracker:

https://github.com/obi-ontology/obi/issues

**Comment by Daniel-Olson** [comment]
1000 commits later and I believe it is good-to-go! @matentzn Thank you for your invaluable guidance! I await further instructions.

**Comment by matentzn** [comment]
I think the next step is to add the pull request to OBI. I also do not know why the GitHub interface does not allow me to declare a PR to the primary project.

Do this:
- Copy the file contents of https://github.com/Daniel-Olson/obi/edit/Cpath_FARS-NTR/src/ontology/templates/assays.tsv?pr=%2FDaniel-Olson%2Fobi%2Fpull%2F1
- paste these file contents into https://github.com/obi-ontology/obi/edit/master/src/ontology/templates/assays.tsv
- Create a pull request, linking to all relevant issues you created on the OBI tracker and saying in one sentence what you are doing (a summary).

**Comment by Daniel-Olson** [comment]
Hi @matentzn. I followed your instructions so we will wait to see how they respond. I wonder if the issue is that we don't have write access to the OBI repo? Thanks.

**Comment by matentzn** [comment]
Excellent! I dont think anything will happen before the new year, but looks good to me!

**Pull request merged**
